### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by evandrocoan**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Thanks for taking the time to submit these. I'm not the maintainer, but I did a quick review anyway since wbond is unlikely to have time for this.

- 171e314: *Added missing LICENSE*
  This is unnecessary when there is a file named `license` in the repo.
- 9163838: *Set to recursively search for the package_control_channel directory*
  I don't exactly see a practical use for this either. Just add the directory to your folders when you want to run the tests. Going through an arbitrarily deeply nested folder structure will only increase the surface for errors, e.g. unprecedented runtime. (Also, you'd actually want to check `dirs` in the loop.)
- ~~e8d3af8: *Created a .no-sublime-package for all packages, in attempt to fix*~~
- ~~a6f2750: *Revert "Created a .no-sublime-package for all packages, in attempt to…*~~
- 315c266: *Set to run the tests command on a background thread*
  ec4a0da: *Set to show a message warning when running commands*
  d633a36: *Removed duplicate function code*
  d2fd3d9: *Replaced duplicated try...finally by decorator*
  I grouped the above, since they are related (and should probably be squashed).
  Adding a mutex to the running commands is a good idea, although I'd instead add a decorator around the entire `run` method since their structure is almost identical. Furthermore, I'd use an actual global boolean instead of a faux static class, because that's essentially what it's used as. Always prefer the more direct approach.
- 49f1a17: *Set to show the output results on output.exec panel*
  The exec panel is for the exec command. We shouldn't be re-using it, even though we are showing "output". It's out own output after all.
- 2d7aee1: *Set to warn the user when some command failed*
  Neutral on this.

Finally, you should adhere to the coding style of the repository you're suggesting changes fore. Notably, that means not adding whitespace inside function calls.

**Review by FichteFoll — COMMENTED** [review]
Thanks for taking the time to submit these. I'm not the maintainer, but I did a quick review anyway since wbond is unlikely to have time for this.

- 171e314: *Added missing LICENSE*
  This is unnecessary when there is a file named `license` in the repo.
- 9163838: *Set to recursively search for the package_control_channel directory*
  I don't exactly see a practical use for this either. Just add the directory to your folders when you want to run the tests. Going through an arbitrarily deeply nested folder structure will only increase the surface for errors, e.g. unprecedented runtime. (Also, you'd actually want to check `dirs` in the loop.)
- ~~e8d3af8: *Created a .no-sublime-package for all packages, in attempt to fix*~~
- ~~a6f2750: *Revert "Created a .no-sublime-package for all packages, in attempt to…*~~
- 315c266: *Set to run the tests command on a background thread*
  ec4a0da: *Set to show a message warning when running commands*
  d633a36: *Removed duplicate function code*
  d2fd3d9: *Replaced duplicated try...finally by decorator*
  I grouped the above, since they are related (and should probably be squashed).
  Adding a mutex to the running commands is a good idea, although I'd instead add a decorator around the entire `run` method since their structure is almost identical. Furthermore, I'd use an actual global boolean instead of a faux static class, because that's essentially what it's used as. Always prefer the more direct approach.
- 49f1a17: *Set to show the output results on output.exec panel*
  The exec panel is for the exec command. We shouldn't be re-using it, even though we are showing "output". It's out own output after all.
- 2d7aee1: *Set to warn the user when some command failed*
  Neutral on this.

Finally, you should adhere to the coding style of the repository you're suggesting changes fore. Notably, that means not adding whitespace inside function calls.

**Comment by evandrocoan** [comment]
How did you do this bullet comments with commit links and messages? 

> * [171e314](https://github.com/wbond/ChannelRepositoryTools/commit/171e3143d233c9d8bda963d1891832be8e23aaab): _Added missing LICENSE_
>   This is unnecessary when there is a file named `license` in the repo.

Now there is a link there too.


> * [9163838](https://github.com/wbond/ChannelRepositoryTools/commit/91638385094844076ac0495b3ff6e23b7bb165b6): _Set to recursively search for the package_control_channel directory_
>   I don't exactly see a practical use for this either. Just add the directory to your folders when you want to run the tests. Going through an arbitrarily deeply nested folder structure will only increase the surface for errors, e.g. unprecedented runtime. (Also, you'd actually want to check `dirs` in the loop.)

It is working. By default, it only finds your this repository if it is on the top level. I added this because I have it nested deep inside an bigger project.

> * ~[e8d3af8](https://github.com/wbond/ChannelRepositoryTools/commit/e8d3af8fd8dfe8be79f7a2084417373d2da68d24): _Created a .no-sublime-package for all packages, in attempt to fix_~
> * ~[a6f2750](https://github.com/wbond/ChannelRepositoryTools/commit/a6f2750717018dfb093ddf379719f3bdce34d29c): _Revert "Created a .no-sublime-package for all packages, in attempt to…_~
> * [315c266](https://github.com/wbond/ChannelRepositoryTools/commit/315c26610ea0d3724e3f8926de82fb410b97d05e): _Set to run the tests command on a background thread_
>   [ec4a0da](https://github.com/wbond/ChannelRepositoryTools/commit/ec4a0dac53f7f41c783538ab9f4e7c2efa79b94a): _Set to show a message warning when running commands_
>   [d633a36](https://github.com/wbond/ChannelRepositoryTools/commit/d633a36288f1b4557ee4fb2a50060bab67030865): _Removed duplicate function code_
>   [d2fd3d9](https://github.com/wbond/ChannelRepositoryTools/commit/d2fd3d945e0ff5144feec9e5b94ebb85a595adaf): _Replaced duplicated try...finally by decorator_
>   I grouped the above, since they are related (and should probably be squashed).

I Squashed them.


>   Adding a mutex to the running commands is a good idea, although I'd instead add a decorator around the entire `run` method since their structure is almost identical. Furthermore, I'd use an actual global boolean instead of a faux static class, because that's essentially what it's used as. Always prefer the more direct approach.

I added a lock and a super decorator.


> * [49f1a17](https://github.com/wbond/ChannelRepositoryTools/commit/49f1a173a4f563550314934e6b9cf8e121b32f81): _Set to show the output results on output.exec panel_
>   The exec panel is for the exec command. We shouldn't be re-using it, even though we are showing "output". It's out own output after all.

I added a setting to name the panel you would like.

**Comment by FichteFoll** [comment]
>How did you do this bullet comments with commit links and messages?

I just copied the commit hashes and commit messages from this page and modified them with multiple selections in ST. Github automatically creates links for 7+-digit hashes in text.

>It is working. By default, it only finds your this repository if it is on the top level. I added this because I have it nested deep inside an bigger project.

I didn't say it wasn't. It's up to you if you prefer a deeply nested project, but you need to consider the average user and their use case, which is most certainly not doing what you do and then you get all the downsides I mentioned earlier. This is a case of over-engineering.

>I added a setting to name the panel you would like.

As is this. Nobody (besides you, maybe?) will ever use this. I guarantee that.

Good work on the lock.

**Comment by evandrocoan** [comment]
Thanks for reviewing the code!

> I just copied the commit hashes and commit messages from this page and modified them with multiple selections in ST. Github automatically creates links for 7+-digit hashes in text.

Nice!

> average user and their use case, which is most certainly not doing what you do and then you get all the downsides I mentioned earlier.

Well, I just added a setting default to disabled. Then, now they will only have an overhead if they enable it.

> Nobody (besides you, maybe?) will ever use this.

Nooo way. From 7 billion of people, I cannot be the only one insane like that!

**Pull request closed without merging**
